name: Publish NuGet

on:
  push:
    tags:
      - 'v*'

permissions: read-all

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup .NET
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5
        with:
          dotnet-version: |
            8.0.x
            10.0.x

      - name: Restore
        run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Pack
        run: dotnet pack -c Release --no-build -o ./artifacts

      - name: NuGet Login
        uses: NuGet/login@8d196754b4036150537f80ac539e15c2f1028841 # v1
        id: login
        with:
          user: fabyoguima

      - name: Publish
        env:
          NUGET_API_KEY: ${{ steps.login.outputs.NUGET_API_KEY }}
        run: dotnet nuget push "./artifacts/*.nupkg" --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json --skip-duplicate
